### ISSUE TITLE
Can't write inside the advance loop bar.

### ISSUE THREAD

**Issue by Hummus23** [losnappas/Custom-Loop#4]
I'm using Firefox nightly latest version and since a month ago the browser got updated and now I can't write inside the advance bar(see picture).
![screenshot_2018-08-13 mov_bbb mp4](https://user-images.githubusercontent.com/42347721/44036206-ec038704-9f19-11e8-8d0a-a70f2724ee41.png)

It's only happening when I use "View video" function or open any video from my PC.
Thanks in advance for any help.

**Comment by losnappas** [comment]
Happens to me too on Firefox dev edition. It's a bug unrelated to the addon. I reported it onward.

https://bugzilla.mozilla.org/show_bug.cgi?id=1484544

**Comment by Hummus23** [comment]
Thanks for reporting it.
